import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import '@fontsource-variable/roboto';
import '@fontsource-variable/fira-code';
import '@fortawesome/fontawesome-free/css/all.css';

import './globals.css';

export const metadata: Metadata = {
	title: 'Chatting app',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en">
			<body className="antialiased">{children}</body>
		</html>
	);
}
